#!/sbin/openrc-run
# Copyright 2016-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

description="ntpd-rs NTP metrics exporter"
pidfile="/run/${RC_SVCNAME}.pid"
user=ntp
group=ntp

command="/usr/bin/ntp-metrics-exporter"
command_background="true"
command_user="${user}:${group}"

depend() {
	after net net-online
}

start_pre() {
	checkpath -q -d -m 0755 -o ${user}:${group} /run/ntpd-rs
}
